---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "lksg-tool-irs.fullname" . }}-service
  namespace: {{ .Values.lksg_tool_irs.namespace }}
  labels:
    {{- include "lksg-tool-irs.labels" . | nindent 4 }}
    application-irs: {{ include "lksg-tool-irs.fullname" . }}-irs
spec:
  type: {{ .Values.lksg_tool_irs.service.type }}
  ports:
    - port: {{ .Values.lksg_tool_irs.apps.irs.port }}
      targetPort: {{ .Values.lksg_tool_irs.apps.irs.targetPort }}
      protocol: {{ .Values.lksg_tool_irs.service.protocol }}
      name: http
  selector:
    {{- include "lksg-tool-irs.selectorLabels" . | nindent 4 }}
