DELETE http://localhost:9999/ess/bpn/investigations/
###
GET http://lksg.tool.localdev.me/ess/bpn/investigations/
###
POST http://lksg.tool.localdev.me/ess/bpn/investigations/
Content-Type: application/json

{
  "bomLifecycle": "asBuilt",
  "callbackUrl": "https://hostname.com/callback?jobId={jobId}&jobState={jobState}",
  "globalAssetId": "urn:uuid:6c311d29-5753-46d4-b32c-19b918ea93b0",
  "incidentBpns": [
    "BPN0000000000001"
  ]
}
###

PUT http://localhost:9999/ess/bpn/investigations/58e67b00-ea43-4984-9ec5-c726559870a2/analysis/COMPLETED/NO/SingleLevelUsageAsBuilt
###

PUT http://localhost:9999/ess/bpn/investigations/19103997-fd08-4afe-86bc-4385789e0199/analysis/COMPLETED/Unknown/SingleLevelUsageAsBuilt
###
PUT http://localhost:9999/ess/bpn/investigations/0676c197-31da-4a6e-b6e8-1da38acb663b/analysis/RUNNING/Unknown/SingleLevelUsageAsBuilt
###